In [187]:
using NBInclude
@nbinclude("main.ipynb")

[1 3 3 3; 2 2 3 2; 1 2 2 3]
[1, 1, 2]

3×5 Matrix{Int64}:
 1  3  3  3  1
 2  2  3  2  1
 1  2  2  3  2

4×4 Matrix{Int64}:
 1  0  0  0
 3  2  0  0
 0  0  0  0
 0  0  0  0

Exchanging row 1 woth row 2

4×4 Matrix{Int64}:
 3  2  0  0
 1  0  0  0
 0  0  0  0
 0  0  0  0

Exchanging row 1 woth row 2

3×5 Matrix{Int64}:
 2  2  3  2  1
 1  3  3  3  1
 1  2  2  3  2

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 3 
Subtracting Row 1 from Row 3 
factor of subtraction = 3 
Exchanging row 2 woth row 3

3×5 Matrix{Int64}:
 2  2  3  2  1
 0  3  0  2  1
 0  2  1  2  2

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 3 
Inside the check for the final Row Pivot
Rank = 3
Consistent = true
[1, 1, 1, 0, 0]


3×5 Matrix{Int64}:
 2  2  3  2  1
 0  3  0  2  1
 0  0  1  3  1

Exchanging row 1 woth row 2

3×5 Matrix{Int64}:
 2  2  3  2  1
 1  3  3  3  1
 1  2  2  3  2

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 3 
Subtracting Row 1 from Row 3 
factor of subtraction = 3 
Exchanging row 2 woth row 3

3×5 Matrix{Int64}:
 2  2  3  2  1
 0  3  0  2  1
 0  2  1  2  2

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 3 
Inside the check for the final Row Pivot
Rank = 3
Consistent = true
[1, 1, 1, 0, 0]


(3, [1 3 3 3; 2 2 3 2; 1 2 2 3], true)

In [188]:
A = ones(Int64, m, n)
b = ones(Int64, m)
rankconsistency(A, b)

3×5 Matrix{Int64}:
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 1 
Subtracting Row 1 from Row 3 
factor of subtraction = 1 
The column 2 is a Zero Column 
The column 3 is a Zero Column 
The column 4 is a Zero Column 
The column 5 is a Zero Column 
Ending the Process prematurely at row = 2
Rank = 1
Consistent = true
[1, 0, 0, 0, 0]


(1, [1 1 1 1; 1 1 1 1; 1 1 1 1], true)

In [189]:
#test more rigorously with special cases

In [190]:
include("EE5609TeamID15.jl")

UpperEchelonNew

In [191]:
using JLD2

In [192]:
@load("Examples_Prog_1/Samples_Prog_1.jld2")
print(Samples[1])

(m = 2, n = 3, A = [0 0 1; 0 0 1], b = [3, 0], U = [0 0 1; 0 0 0], r = 1, consistent = false)

In [193]:
num = 20
i = 0
for sample in Samples
    @printf("\n ###################### Testing Case %d ###################################### \n", i+1)
    print("Input Matrix = ")
    display(sample.A)
    U, Rank, consistent = rankconsistencyTeamID15(sample.A, sample.b)
    i = i + 1
    if(i >= num)
        break
    end
    if(consistent == sample.consistent && sample.r == Rank && sample.U == U)
        @printf("\n-------------------Test case %d has passed -------------------------------\n", i)
    else
        @printf("\n-------------------Test case %d has failed -------------------------------\n", i)
        println("Is supposed to be ", sample.consistent, " but found to be = ", consistent)
        @printf("\n %d != %d\n", Rank, sample.r)
        print("Expected U = ")
        display(sample.U)
    end
end


 ###################### Testing Case 1 ###################################### 
Input Matrix = 

2×3 Matrix{Int64}:
 0  0  1
 0  0  1

The column 1 is a Zero Column 
The column 2 is a Zero Column 


2×4 Matrix{Int64}:
 0  0  1  3
 0  0  1  0

(1, 3) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 1 
Inside the check for the final Row Pivot
Rank = 1
Consistent = false
[0, 0, 1, 1]
~~~~~~~~Row reduction process complete~~~~~


2×3 Matrix{Int64}:
 0  0  1
 0  0  0


-------------------Test case 1 has passed -------------------------------

 ###################### Testing Case 2 ###################################### 
Input Matrix = 

2×3 Matrix{Int64}:
 0  1  1
 2  0  1

Exchanging row 1 woth row 2

2×4 Matrix{Int64}:
 2  0  1  2
 0  1  1  0

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 0 
Inside the check for the final Row Pivot
Rank = 2
Consistent = true
[1, 1, 0, 0]
~~~~~~~~Row reduction process complete~~~~~


2×3 Matrix{Int64}:
 2  0  1
 0  1  1


-------------------Test case 2 has passed -------------------------------

 ###################### Testing Case 3 ###################################### 
Input Matrix = 

2×3 Matrix{Int64}:
 0  1  1
 0  1  1

The column 1 is a Zero Column 


2×4 Matrix{Int64}:
 0  1  1  1
 0  1  1  3

(1, 2) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 1 
Inside the check for the final Row Pivot
Rank = 1
Consistent = false
[0, 1, 0, 1]
~~~~~~~~Row reduction process complete~~~~~


2×3 Matrix{Int64}:
 0  1  1
 0  0  0


-------------------Test case 3 has passed -------------------------------

 ###################### Testing Case 4 ###################################### 
Input Matrix = 

2×3 Matrix{Int64}:
 2  0  0
 2  0  2

2×4 Matrix{Int64}:
 2  0  0  0
 2  0  2  1

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 1 
Inside the check for the final Row Pivot
Rank = 2
Consistent = true
[1, 0, 1, 0]
~~~~~~~~Row reduction process complete~~~~~


2×3 Matrix{Int64}:
 2  0  0
 0  0  2


-------------------Test case 4 has passed -------------------------------

 ###################### Testing Case 5 ###################################### 
Input Matrix = 

2×3 Matrix{Int64}:
 0  0  0
 2  3  0

Exchanging row 1 woth row 2

2×4 Matrix{Int64}:
 2  3  0  0
 0  0  0  2

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 0 
Inside the check for the final Row Pivot
Rank = 1
Consistent = false
[1, 0, 0, 1]
~~~~~~~~Row reduction process complete~~~~~


2×3 Matrix{Int64}:
 2  3  0
 0  0  0


-------------------Test case 5 has passed -------------------------------

 ###################### Testing Case 6 ###################################### 
Input Matrix = 

3×2 Matrix{Int64}:
 2  3
 0  0
 3  3

Exchanging row 1 woth row 3

3×3 Matrix{Int64}:
 3  3  2
 0  0  2
 2  3  1

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 0 
Subtracting Row 1 from Row 3 
factor of subtraction = 3 
Exchanging row 2 woth row 3

3×3 Matrix{Int64}:
 3  3  2
 0  1  0
 0  0  2

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 0 
Inside the check for the final Row Pivot
Rank = 2
Consistent = false
[1, 1, 1]
~~~~~~~~Row reduction process complete~~~~~


3×2 Matrix{Int64}:
 3  3
 0  1
 0  0


-------------------Test case 6 has passed -------------------------------

 ###################### Testing Case 7 ###################################### 
Input Matrix = 

3×2 Matrix{Int64}:
 0  2
 1  0
 3  0

Exchanging row 1 woth row 3

3×3 Matrix{Int64}:
 3  0  0
 1  0  0
 0  2  0

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 2 
Subtracting Row 1 from Row 3 
factor of subtraction = 0 
Exchanging row 2 woth row 3

3×3 Matrix{Int64}:
 3  0  0
 0  2  0
 0  0  0

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 0 
Inside the check for the final Row Pivot
Rank = 2
Consistent = true
[1, 1, 0]
~~~~~~~~Row reduction process complete~~~~~


3×2 Matrix{Int64}:
 3  0
 0  2
 0  0


-------------------Test case 7 has passed -------------------------------

 ###################### Testing Case 8 ###################################### 
Input Matrix = 

3×2 Matrix{Int64}:
 3  1
 3  3
 0  1

3×3 Matrix{Int64}:
 3  1  3
 3  3  3
 0  1  3

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 1 
Subtracting Row 1 from Row 3 
factor of subtraction = 0 


3×3 Matrix{Int64}:
 3  1  3
 0  2  0
 0  1  3

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 3 
Inside the check for the final Row Pivot
Rank = 2
Consistent = false
[1, 1, 1]
~~~~~~~~Row reduction process complete~~~~~


3×2 Matrix{Int64}:
 3  1
 0  2
 0  0


-------------------Test case 8 has passed -------------------------------

 ###################### Testing Case 9 ###################################### 
Input Matrix = 

3×2 Matrix{Int64}:
 2  2
 3  0
 2  0

Exchanging row 1 woth row 2

3×3 Matrix{Int64}:
 3  0  2
 2  2  2
 2  0  1

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 3 
Subtracting Row 1 from Row 3 
factor of subtraction = 3 


3×3 Matrix{Int64}:
 3  0  2
 0  2  3
 0  0  0

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 0 
Inside the check for the final Row Pivot
Rank = 2
Consistent = true
[1, 1, 0]
~~~~~~~~Row reduction process complete~~~~~


3×2 Matrix{Int64}:
 3  0
 0  2
 0  0


-------------------Test case 9 has passed -------------------------------

 ###################### Testing Case 10 ###################################### 
Input Matrix = 

3×2 Matrix{Int64}:
 2  1
 3  2
 2  3

Exchanging row 1 woth row 2

3×3 Matrix{Int64}:
 3  2  3
 2  1  1
 2  3  1

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 3 
Subtracting Row 1 from Row 3 
factor of subtraction = 3 
Exchanging row 2 woth row 3

3×3 Matrix{Int64}:
 3  2  3
 0  2  3
 0  0  3

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 0 
Inside the check for the final Row Pivot
Rank = 2
Consistent = false
[1, 1, 1]
~~~~~~~~Row reduction process complete~~~~~


3×2 Matrix{Int64}:
 3  2
 0  2
 0  0


-------------------Test case 10 has passed -------------------------------

 ###################### Testing Case 11 ###################################### 
Input Matrix = 

3×3 Matrix{Int64}:
 3  0  1
 3  1  2
 3  0  1

3×4 Matrix{Int64}:
 3  0  1  1
 3  1  2  0
 3  0  1  0

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 1 
Subtracting Row 1 from Row 3 
factor of subtraction = 1 


3×4 Matrix{Int64}:
 3  0  1  1
 0  1  3  1
 0  0  0  1

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 0 
Inside the check for the final Row Pivot
Rank = 2
Consistent = false
[1, 1, 0, 1]
~~~~~~~~Row reduction process complete~~~~~


3×3 Matrix{Int64}:
 3  0  1
 0  1  3
 0  0  0


-------------------Test case 11 has passed -------------------------------

 ###################### Testing Case 12 ###################################### 
Input Matrix = 

3×3 Matrix{Int64}:
 1  0  3
 2  1  1
 3  2  2

Exchanging row 1 woth row 3

3×4 Matrix{Int64}:
 3  2  2  1
 2  1  1  3
 1  0  3  1

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 3 
Subtracting Row 1 from Row 3 
factor of subtraction = 2 
Exchanging row 2 woth row 3

3×4 Matrix{Int64}:
 3  2  2  1
 0  3  0  3
 0  0  0  0

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 0 
Inside the check for the final Row Pivot
Rank = 2
Consistent = true
[1, 1, 0, 0]
~~~~~~~~Row reduction process complete~~~~~


3×3 Matrix{Int64}:
 3  2  2
 0  3  0
 0  0  0


-------------------Test case 12 has passed -------------------------------

 ###################### Testing Case 13 ###################################### 
Input Matrix = 

3×3 Matrix{Int64}:
 3  2  1
 2  2  0
 1  0  1

3×4 Matrix{Int64}:
 3  2  1  1
 2  2  0  1
 1  0  1  3

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 3 
Subtracting Row 1 from Row 3 
factor of subtraction = 2 


3×4 Matrix{Int64}:
 3  2  1  1
 0  3  3  2
 0  3  3  1

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 1 
Inside the check for the final Row Pivot
Rank = 2
Consistent = false
[1, 1, 0, 1]
~~~~~~~~Row reduction process complete~~~~~


3×3 Matrix{Int64}:
 3  2  1
 0  3  3
 0  0  0


-------------------Test case 13 has passed -------------------------------

 ###################### Testing Case 14 ###################################### 
Input Matrix = 

3×3 Matrix{Int64}:
 2  2  0
 0  3  3
 0  2  0

3×4 Matrix{Int64}:
 2  2  0  1
 0  3  3  2
 0  2  0  1

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 0 
Subtracting Row 1 from Row 3 
factor of subtraction = 0 


3×4 Matrix{Int64}:
 2  2  0  1
 0  3  3  2
 0  2  0  1

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 3 
Inside the check for the final Row Pivot
Rank = 3
Consistent = true
[1, 1, 1, 0]
~~~~~~~~Row reduction process complete~~~~~


3×3 Matrix{Int64}:
 2  2  0
 0  3  3
 0  0  2


-------------------Test case 14 has passed -------------------------------

 ###################### Testing Case 15 ###################################### 
Input Matrix = 

3×3 Matrix{Int64}:
 3  1  3
 1  2  1
 1  0  3

3×4 Matrix{Int64}:
 3  1  3  3
 1  2  1  0
 1  0  3  2

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 2 
Subtracting Row 1 from Row 3 
factor of subtraction = 2 
Exchanging row 2 woth row 3

3×4 Matrix{Int64}:
 3  1  3  3
 0  2  2  3
 0  0  0  1

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 0 
Inside the check for the final Row Pivot
Rank = 2
Consistent = false
[1, 1, 0, 1]
~~~~~~~~Row reduction process complete~~~~~


3×3 Matrix{Int64}:
 3  1  3
 0  2  2
 0  0  0


-------------------Test case 15 has passed -------------------------------

 ###################### Testing Case 16 ###################################### 
Input Matrix = 

4×4 Matrix{Int64}:
 2  3  3  0
 0  1  2  3
 0  1  2  3
 2  2  0  2

4×5 Matrix{Int64}:
 2  3  3  0  1
 0  1  2  3  2
 0  1  2  3  3
 2  2  0  2  1

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 0 
Subtracting Row 1 from Row 3 
factor of subtraction = 0 
Subtracting Row 1 from Row 4 
factor of subtraction = 1 


4×5 Matrix{Int64}:
 2  3  3  0  1
 0  1  2  3  2
 0  1  2  3  3
 0  1  3  2  0

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 1 
Subtracting Row 2 from Row 4 
factor of subtraction = 1 
Exchanging row 3 woth row 4

4×5 Matrix{Int64}:
 2  3  3  0  1
 0  1  2  3  2
 0  0  1  1  2
 0  0  0  0  1

(3, 3) is a pivot position
Subtracting Row 3 from Row 4 
factor of subtraction = 0 
Inside the check for the final Row Pivot
Rank = 3
Consistent = false
[1, 1, 1, 0, 1]
~~~~~~~~Row reduction process complete~~~~~


4×4 Matrix{Int64}:
 2  3  3  0
 0  1  2  3
 0  0  1  1
 0  0  0  0


-------------------Test case 16 has passed -------------------------------

 ###################### Testing Case 17 ###################################### 
Input Matrix = 

4×4 Matrix{Int64}:
 0  3  1  1
 2  0  0  3
 3  3  2  0
 0  2  3  1

Exchanging row 1 woth row 3

4×5 Matrix{Int64}:
 3  3  2  0  1
 2  0  0  3  0
 0  3  1  1  3
 0  2  3  1  1

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 3 
Subtracting Row 1 from Row 3 
factor of subtraction = 0 
Subtracting Row 1 from Row 4 
factor of subtraction = 0 
Exchanging row 2 woth row 3

4×5 Matrix{Int64}:
 3  3  2  0  1
 0  3  1  1  3
 0  2  1  3  3
 0  2  3  1  1

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 3 
Subtracting Row 2 from Row 4 
factor of subtraction = 3 


4×5 Matrix{Int64}:
 3  3  2  0  1
 0  3  1  1  3
 0  0  2  0  1
 0  0  0  2  3

(3, 3) is a pivot position
Subtracting Row 3 from Row 4 
factor of subtraction = 0 
Inside the check for the final Row Pivot
Rank = 4
Consistent = true
[1, 1, 1, 1, 0]
~~~~~~~~Row reduction process complete~~~~~


4×4 Matrix{Int64}:
 3  3  2  0
 0  3  1  1
 0  0  2  0
 0  0  0  2


-------------------Test case 17 has passed -------------------------------

 ###################### Testing Case 18 ###################################### 
Input Matrix = 

4×4 Matrix{Int64}:
 3  0  1  3
 3  1  2  0
 0  1  1  2
 2  2  1  1

4×5 Matrix{Int64}:
 3  0  1  3  2
 3  1  2  0  1
 0  1  1  2  0
 2  2  1  1  2

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 1 
Subtracting Row 1 from Row 3 
factor of subtraction = 0 
Subtracting Row 1 from Row 4 
factor of subtraction = 3 
Exchanging row 2 woth row 4

4×5 Matrix{Int64}:
 3  0  1  3  2
 0  2  2  3  3
 0  1  1  2  0
 0  1  3  3  3

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 3 
Subtracting Row 2 from Row 4 
factor of subtraction = 3 
Exchanging row 3 woth row 4

4×5 Matrix{Int64}:
 3  0  1  3  2
 0  2  2  3  3
 0  0  2  1  1
 0  0  0  0  2

(3, 3) is a pivot position
Subtracting Row 3 from Row 4 
factor of subtraction = 0 
Inside the check for the final Row Pivot
Rank = 3
Consistent = false
[1, 1, 1, 0, 1]
~~~~~~~~Row reduction process complete~~~~~


4×4 Matrix{Int64}:
 3  0  1  3
 0  2  2  3
 0  0  2  1
 0  0  0  0


-------------------Test case 18 has passed -------------------------------

 ###################### Testing Case 19 ###################################### 
Input Matrix = 

4×4 Matrix{Int64}:
 3  0  2  2
 1  1  1  0
 2  1  3  0
 1  1  0  0

4×5 Matrix{Int64}:
 3  0  2  2  2
 1  1  1  0  3
 2  1  3  0  2
 1  1  0  0  2

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 2 
Subtracting Row 1 from Row 3 
factor of subtraction = 3 
Subtracting Row 1 from Row 4 
factor of subtraction = 2 


4×5 Matrix{Int64}:
 3  0  2  2  2
 0  1  2  3  0
 0  1  2  1  3
 0  1  3  3  1

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 1 
Subtracting Row 2 from Row 4 
factor of subtraction = 1 
Exchanging row 3 woth row 4

4×5 Matrix{Int64}:
 3  0  2  2  2
 0  1  2  3  0
 0  0  1  0  1
 0  0  0  2  3

(3, 3) is a pivot position
Subtracting Row 3 from Row 4 
factor of subtraction = 0 
Inside the check for the final Row Pivot
Rank = 4
Consistent = true
[1, 1, 1, 1, 0]
~~~~~~~~Row reduction process complete~~~~~


4×4 Matrix{Int64}:
 3  0  2  2
 0  1  2  3
 0  0  1  0
 0  0  0  2


-------------------Test case 19 has passed -------------------------------

 ###################### Testing Case 20 ###################################### 
Input Matrix = 

4×4 Matrix{Int64}:
 1  0  0  2
 2  2  1  1
 1  0  1  3
 0  2  0  3

Exchanging row 1 woth row 2

4×5 Matrix{Int64}:
 2  2  1  1  2
 1  0  0  2  3
 1  0  1  3  0
 0  2  0  3  1

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 3 
Subtracting Row 1 from Row 3 
factor of subtraction = 3 
Subtracting Row 1 from Row 4 
factor of subtraction = 0 
Exchanging row 2 woth row 4

4×5 Matrix{Int64}:
 2  2  1  1  2
 0  2  0  3  1
 0  1  2  0  1
 0  1  3  1  2

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 3 
Subtracting Row 2 from Row 4 
factor of subtraction = 3 
Exchanging row 3 woth row 4

4×5 Matrix{Int64}:
 2  2  1  1  2
 0  2  0  3  1
 0  0  3  3  1
 0  0  2  2  2

(3, 3) is a pivot position
Subtracting Row 3 from Row 4 
factor of subtraction = 3 
Inside the check for the final Row Pivot
Rank = 3
Consistent = false
[1, 1, 1, 0, 1]
~~~~~~~~Row reduction process complete~~~~~


4×4 Matrix{Int64}:
 2  2  1  1
 0  2  0  3
 0  0  3  3
 0  0  0  0