In [16]:
using NBInclude
@nbinclude("main.ipynb")

[1 3 3 3; 2 2 3 2; 1 2 2 3]
[1, 1, 2]

3×5 Matrix{Int64}:
 1  3  3  3  1
 2  2  3  2  1
 1  2  2  3  2

4×4 Matrix{Int64}:
 1  0  0  0
 3  2  0  0
 0  0  0  0
 0  0  0  0

Exchanging row 1 woth row 2

4×4 Matrix{Int64}:
 3  2  0  0
 1  0  0  0
 0  0  0  0
 0  0  0  0

Exchanging row 1 woth row 2

3×5 Matrix{Int64}:
 2  2  3  2  1
 1  3  3  3  1
 1  2  2  3  2

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 3 
Subtracting Row 1 from Row 3 
factor of subtraction = 3 
Exchanging row 2 woth row 3

3×5 Matrix{Int64}:
 2  2  3  2  1
 0  3  0  2  1
 0  2  1  2  2

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 3 
Inside the check for the final Row Pivot
Rank = 3
Consistent = true
[1, 1, 1, 0, 0]


3×5 Matrix{Int64}:
 2  2  3  2  1
 0  3  0  2  1
 0  0  1  3  1

Exchanging row 1 woth row 2

3×4 Matrix{Int64}:
 2  2  3  2
 1  3  3  3
 1  2  2  3

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 3 
Subtracting Row 1 from Row 3 
factor of subtraction = 3 
Exchanging row 2 woth row 3

3×4 Matrix{Int64}:
 2  2  3  2
 0  3  0  2
 0  2  1  2

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 3 
Inside the check for the final Row Pivot
Rank = 3
Consistent = true
[1, 1, 1, 0]


(3, [2 2 3 2; 0 3 0 2; 0 0 1 3], true)

In [20]:
A = ones(Int64, m, n)
b = ones(Int64, m)
rankconsistency(A, b)

3×4 Matrix{Int64}:
 1  1  1  1
 1  1  1  1
 1  1  1  1

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 1 
Subtracting Row 1 from Row 3 
factor of subtraction = 1 
The column 2 is a Zero Column 
The column 3 is a Zero Column 
The column 4 is a Zero Column 
Ending the Process prematurely at row = 2
Rank = 1
Consistent = true
[1, 0, 0, 0]


(1, [1 1 1 1; 0 0 0 0; 0 0 0 0], true)

In [ ]:
#test more rigorously with special cases