In [1]:
using NBInclude
@nbinclude("main.ipynb")

[1 3 3 3; 2 2 3 2; 1 2 2 3]
[1, 1, 2]

3×5 Matrix{Int64}:
 1  3  3  3  1
 2  2  3  2  1
 1  2  2  3  2

4×4 Matrix{Int64}:
 1  0  0  0
 3  2  0  0
 0  0  0  0
 0  0  0  0

Exchanging row 1 woth row 2

4×4 Matrix{Int64}:
 3  2  0  0
 1  0  0  0
 0  0  0  0
 0  0  0  0

Exchanging row 1 woth row 2

3×5 Matrix{Int64}:
 2  2  3  2  1
 1  3  3  3  1
 1  2  2  3  2

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 3 
Subtracting Row 1 from Row 3 
factor of subtraction = 3 
Exchanging row 2 woth row 3

3×5 Matrix{Int64}:
 2  2  3  2  1
 0  3  0  2  1
 0  2  1  2  2

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 3 
Inside the check for the final Row Pivot
Rank = 3
Consistent = true
[1, 1, 1, 0, 0]


3×5 Matrix{Int64}:
 2  2  3  2  1
 0  3  0  2  1
 0  0  1  3  1

Exchanging row 1 woth row 2

3×5 Matrix{Int64}:
 2  2  3  2  1
 1  3  3  3  1
 1  2  2  3  2

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 3 
Subtracting Row 1 from Row 3 
factor of subtraction = 3 
Exchanging row 2 woth row 3

3×5 Matrix{Int64}:
 2  2  3  2  1
 0  3  0  2  1
 0  2  1  2  2

(2, 2) is a pivot position
Subtracting Row 2 from Row 3 
factor of subtraction = 3 
Inside the check for the final Row Pivot
Rank = 3
Consistent = true
[1, 1, 1, 0, 0]


([2 2 3 2; 0 3 0 2; 0 0 1 3], 3, true)

In [2]:
A = ones(Int64, m, n)
b = ones(Int64, m)
rankconsistency(A, b)

3×5 Matrix{Int64}:
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1

(1, 1) is a pivot position
Subtracting Row 1 from Row 2 
factor of subtraction = 1 
Subtracting Row 1 from Row 3 
factor of subtraction = 1 
The column 2 is a Zero Column 
The column 3 is a Zero Column 
The column 4 is a Zero Column 
The column 5 is a Zero Column 
Ending the Process prematurely at row = 2
Rank = 1
Consistent = true
[1, 0, 0, 0, 0]


([1 1 1 1; 0 0 0 0; 0 0 0 0], 1, true)

In [3]:
#test more rigorously with special cases

In [4]:
include("EE5609TeamID15.jl")

UpperEchelonNew

In [5]:
using JLD2

In [6]:
@load("Examples_Prog_1/Samples_Prog_1.jld2")
print(Samples[1])

(m = 2, n = 3, A = [0 0 1; 0 0 1], b = [3, 0], U = [0 0 1; 0 0 0], r = 1, consistent = false)

In [9]:
A = rand(0:3, (100, 100))
b = rand(0:3, (100))
U , rank, consistent = rankconsistencyTeamID15(A, b)

([3 3 … 3 2; 0 3 … 2 0; … ; 0 0 … 3 0; 0 0 … 0 3], 100, true)

In [ ]:
num = 26
i = 1
for sample in Samples
    @printf("----------------------------Testing Case %d ------------------------------------ \n", i+1)
    # print("Input Matrix = ")
    # display(sample.A)
    U, Rank, consistent = rankconsistencyTeamID15(sample.A, sample.b)
    i = i + 1
    if(i >= num)
        break
    end
    if(consistent == sample.consistent && sample.r == Rank && sample.U == U)
        @printf("\n-------------------Test case %d has passed -------------------------------\n", i)
    else
        @printf("\n-------------------Test case %d has failed -------------------------------\n", i)
        println("Is supposed to be ", sample.consistent, " but found to be = ", consistent)
        @printf("\n %d != %d\n", Rank, sample.r)
        # print("Expected U = ")
        # display(sample.U)
    end
end

----------------------------Testing Case 2 ------------------------------------ 

-------------------Test case 2 has passed -------------------------------
----------------------------Testing Case 3 ------------------------------------ 

-------------------Test case 3 has passed -------------------------------
----------------------------Testing Case 4 ------------------------------------ 

-------------------Test case 4 has passed -------------------------------
----------------------------Testing Case 5 ------------------------------------ 

-------------------Test case 5 has passed -------------------------------
----------------------------Testing Case 6 ------------------------------------ 

-------------------Test case 6 has passed -------------------------------
----------------------------Testing Case 7 ------------------------------------ 

-------------------Test case 7 has passed -------------------------------
----------------------------Testing Case 8 ---------------------